# Practice Assignment - Dataset Versioning using DVC

## Objective

The objective of this practice assignment is to understand the workflow of **Dataset Versioning using Data Version Control (DVC)**.

A custom student dataset is created and versioned using DVC. Two versions of the dataset are maintained to demonstrate dataset growth through the addition of new records.

# Version 1 - Initial Student Dataset

## Objective

Create the initial student dataset containing:

- Student_ID
- Name
- Age
- Branch
- CGPA

The dataset initially contains **10 student records** and will be tracked using DVC.

In [1]:
import pandas as pd

In [2]:
students = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": [
        "Aarav","Diya","Kabir","Meera","Rohan",
        "Sneha","Vivaan","Ananya","Aryan","Ishita"
    ],
    "Age": [
        20,21,19,22,20,
        21,23,20,22,19
    ],
    "Branch": [
        "CSE","AI","IT","CSE","AI",
        "ECE","IT","AI","CSE","ECE"
    ],
    "CGPA": [
        8.5,9.1,7.8,8.9,9.3,
        8.0,7.5,9.0,8.4,8.8
    ]
}

In [3]:
df = pd.DataFrame(students)
df

   Student_ID    Name  Age Branch  CGPA
0         101   Aarav   20    CSE   8.5
1         102    Diya   21     AI   9.1
2         103   Kabir   19     IT   7.8
3         104   Meera   22    CSE   8.9
4         105   Rohan   20     AI   9.3
5         106   Sneha   21    ECE   8.0
6         107  Vivaan   23     IT   7.5
7         108  Ananya   20     AI   9.0
8         109   Aryan   22    CSE   8.4
9         110  Ishita   19    ECE   8.8

In [4]:
df.to_csv("../data/students.csv", index=False)
print("Version 1 dataset saved successfully.")

Version 1 dataset saved successfully.

In [5]:
df_loaded = pd.read_csv("../data/students.csv")
df_loaded

   Student_ID    Name  Age Branch  CGPA
0         101   Aarav   20    CSE   8.5
1         102    Diya   21     AI   9.1
2         103   Kabir   19     IT   7.8
3         104   Meera   22    CSE   8.9
4         105   Rohan   20     AI   9.3
5         106   Sneha   21    ECE   8.0
6         107  Vivaan   23     IT   7.5
7         108  Ananya   20     AI   9.0
8         109   Aryan   22    CSE   8.4
9         110  Ishita   19    ECE   8.8

# Version 2 - Add New Student Records

## Objective

Add **three new student records** to the existing dataset.

Changes Made:

- Added three new students.
- Increased dataset size from **10** to **13** records.
- Saved the updated dataset.
- Tracked the updated dataset using DVC.

In [6]:
new_students = pd.DataFrame({
    "Student_ID": [111,112,113],
    "Name": [
        "Rahul",
        "Priya",
        "Karan"
    ],
    "Age": [
        21,
        20,
        22
    ],
    "Branch": [
        "AI",
        "CSE",
        "IT"
    ],
    "CGPA": [
        8.7,
        9.2,
        8.1
    ]
})

In [7]:
df = pd.concat([df, new_students], ignore_index=True)
df

    Student_ID    Name  Age Branch  CGPA
0          101   Aarav   20    CSE   8.5
1          102    Diya   21     AI   9.1
2          103   Kabir   19     IT   7.8
3          104   Meera   22    CSE   8.9
4          105   Rohan   20     AI   9.3
5          106   Sneha   21    ECE   8.0
6          107  Vivaan   23     IT   7.5
7          108  Ananya   20     AI   9.0
8          109   Aryan   22    CSE   8.4
9          110  Ishita   19    ECE   8.8
10         111   Rahul   21     AI   8.7
11         112   Priya   20    CSE   9.2
12         113   Karan   22     IT   8.1

In [8]:
df.to_csv("../data/students.csv", index=False)
print("Version 2 dataset saved successfully.")

Version 2 dataset saved successfully.

In [9]:
df_loaded = pd.read_csv("../data/students.csv")
df_loaded

    Student_ID    Name  Age Branch  CGPA
0          101   Aarav   20    CSE   8.5
1          102    Diya   21     AI   9.1
2          103   Kabir   19     IT   7.8
3          104   Meera   22    CSE   8.9
4          105   Rohan   20     AI   9.3
5          106   Sneha   21    ECE   8.0
6          107  Vivaan   23     IT   7.5
7          108  Ananya   20     AI   9.0
8          109   Aryan   22    CSE   8.4
9          110  Ishita   19    ECE   8.8
10         111   Rahul   21     AI   8.7
11         112   Priya   20    CSE   9.2
12         113   Karan   22     IT   8.1

# Conclusion

In this practice assignment, dataset versioning was implemented using **Data Version Control (DVC)**.

The dataset evolved through two versions:

- **Version 1:** Created the initial student dataset containing **10 records**.
- **Version 2:** Added **three new student records**, increasing the dataset size to **13 records**.

Each version was tracked using **DVC** and committed using **Git**, demonstrating how dataset versions can be managed efficiently in Machine Learning projects.