In [1]:
import pandas as pd

In [6]:
students = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,111,112,113],
    "Name": [
        "Aarav","Diya","Kabir","Meera","Rohan",
        "Sneha","Vivaan","Ananya","Aryan","Ishita",
        "Rahul","Priya","Karan"
    ],
    "Age": [20,21,19,22,20,21,23,20,22,19,21,20,22],
    "Branch": [
        "CSE","AI","IT","CSE","AI",
        "ECE","IT","AI","CSE","ECE",
        "AI","CSE","IT"
    ],
    "CGPA": [8.5,9.1,7.8,8.9,9.3,8.0,7.5,9.0,8.4,8.8,8.7,9.2,8.1]
}

In [7]:
df = pd.DataFrame(students)
df

    Student_ID    Name  Age Branch  CGPA
0          101   Aarav   20    CSE   8.5
1          102    Diya   21     AI   9.1
2          103   Kabir   19     IT   7.8
3          104   Meera   22    CSE   8.9
4          105   Rohan   20     AI   9.3
5          106   Sneha   21    ECE   8.0
6          107  Vivaan   23     IT   7.5
7          108  Ananya   20     AI   9.0
8          109   Aryan   22    CSE   8.4
9          110  Ishita   19    ECE   8.8
10         111   Rahul   21     AI   8.7
11         112   Priya   20    CSE   9.2
12         113   Karan   22     IT   8.1

In [8]:
df.to_csv("../data/students.csv", index=False)

In [9]:
df_loaded = pd.read_csv("../data/students.csv")
df_loaded

    Student_ID    Name  Age Branch  CGPA
0          101   Aarav   20    CSE   8.5
1          102    Diya   21     AI   9.1
2          103   Kabir   19     IT   7.8
3          104   Meera   22    CSE   8.9
4          105   Rohan   20     AI   9.3
5          106   Sneha   21    ECE   8.0
6          107  Vivaan   23     IT   7.5
7          108  Ananya   20     AI   9.0
8          109   Aryan   22    CSE   8.4
9          110  Ishita   19    ECE   8.8
10         111   Rahul   21     AI   8.7
11         112   Priya   20    CSE   9.2
12         113   Karan   22     IT   8.1