In [1]:
import pandas as pd

# Version 1 - Initial Employee Salary Dataset

## Objective
Create the initial employee salary dataset containing:
- Employee_ID
- Employee_Name
- Department
- Salary

This dataset will be tracked using DVC for version control.

In [2]:
employees = {
    "Employee_ID": [201,202,203,204,205,206,207,208,209,210],
    "Employee_Name": [
        "Aarav Sharma","Diya Patel","Kabir Singh","Meera Nair","Rohan Verma",
        "Sneha Iyer","Vivaan Gupta","Ananya Rao","Aryan Mehta","Ishita Kapoor"
    ],
    "Department": [
        "HR","Finance","IT","Marketing","Sales",
        "Operations","IT","Finance","HR","Marketing",
    ],
    "Salary": [
        45000, 60000, 55000, 52000, 48000,
        50000, 65000, 58000, 47000, 54000
    ]
}

In [3]:
df = pd.DataFrame(employees)
df

   Employee_ID  Employee_Name  Department  Salary
0          201   Aarav Sharma          HR   45000
1          202     Diya Patel     Finance   60000
2          203    Kabir Singh          IT   55000
3          204     Meera Nair   Marketing   52000
4          205    Rohan Verma       Sales   48000
5          206     Sneha Iyer  Operations   50000
6          207   Vivaan Gupta          IT   65000
7          208     Ananya Rao     Finance   58000
8          209    Aryan Mehta          HR   47000
9          210  Ishita Kapoor   Marketing   54000

In [4]:
df.to_csv("../data/employees.csv", index=False)
print("Version 1 dataset saved successfully.")

Version 1 dataset saved successfully.

In [5]:
df_loaded = pd.read_csv("../data/employees.csv")
df_loaded

   Employee_ID  Employee_Name  Department  Salary
0          201   Aarav Sharma          HR   45000
1          202     Diya Patel     Finance   60000
2          203    Kabir Singh          IT   55000
3          204     Meera Nair   Marketing   52000
4          205    Rohan Verma       Sales   48000
5          206     Sneha Iyer  Operations   50000
6          207   Vivaan Gupta          IT   65000
7          208     Ananya Rao     Finance   58000
8          209    Aryan Mehta          HR   47000
9          210  Ishita Kapoor   Marketing   54000

# Version 2 - Salary Increment

## Objective

Increase the salary of every employee by **10%** and create a new version of the dataset using DVC.

In [6]:
df["Salary"] = (df["Salary"] * 1.10).round().astype(int)

df

   Employee_ID  Employee_Name  Department  Salary
0          201   Aarav Sharma          HR   49500
1          202     Diya Patel     Finance   66000
2          203    Kabir Singh          IT   60500
3          204     Meera Nair   Marketing   57200
4          205    Rohan Verma       Sales   52800
5          206     Sneha Iyer  Operations   55000
6          207   Vivaan Gupta          IT   71500
7          208     Ananya Rao     Finance   63800
8          209    Aryan Mehta          HR   51700
9          210  Ishita Kapoor   Marketing   59400

In [7]:
df.to_csv("../data/employees.csv", index=False)
print("Version 2 dataset saved successfully.")

Version 2 dataset saved successfully.

In [8]:
df_loaded = pd.read_csv("../data/employees.csv")
df_loaded

   Employee_ID  Employee_Name  Department  Salary
0          201   Aarav Sharma          HR   49500
1          202     Diya Patel     Finance   66000
2          203    Kabir Singh          IT   60500
3          204     Meera Nair   Marketing   57200
4          205    Rohan Verma       Sales   52800
5          206     Sneha Iyer  Operations   55000
6          207   Vivaan Gupta          IT   71500
7          208     Ananya Rao     Finance   63800
8          209    Aryan Mehta          HR   51700
9          210  Ishita Kapoor   Marketing   59400

# Version 3 - Add Years of Experience

## Objective

Add a new column named **Years_of_Experience** to demonstrate dataset schema evolution using DVC.

In [9]:
import random
random.seed(42)
df["Years_of_Experience"] = [
    random.randint(1, 15)
    for _ in range(len(df))
]

In [10]:
df.to_csv("../data/employees.csv", index=False)
print("Version 3 dataset saved successfully.")

Version 3 dataset saved successfully.

In [11]:
df_loaded = pd.read_csv("../data/employees.csv")
df_loaded

   Employee_ID  Employee_Name  Department  Salary  Years_of_Experience
0          201   Aarav Sharma          HR   49500                   11
1          202     Diya Patel     Finance   66000                    2
2          203    Kabir Singh          IT   60500                    1
3          204     Meera Nair   Marketing   57200                   12
4          205    Rohan Verma       Sales   52800                    5
5          206     Sneha Iyer  Operations   55000                    4
6          207   Vivaan Gupta          IT   71500                    4
7          208     Ananya Rao     Finance   63800                    3
8          209    Aryan Mehta          HR   51700                   12
9          210  Ishita Kapoor   Marketing   59400                    2

# Version 4 - Add Performance Rating Column

## Objective

Add a new column named **Performance_Rating** to the employee dataset. This demonstrates another schema evolution where additional employee information is included in the dataset.

Changes Made:
- Added `Performance_Rating` column.
- Saved the updated dataset.
- Tracked the new version using DVC.

In [12]:
df["Performance_Rating"] = [
    "Excellent",
    "Good",
    "Very Good",
    "Excellent",
    "Average",
    "Good",
    "Excellent",
    "Very Good",
    "Good",
    "Average"
]
df

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Aarav Sharma,HR,49500,11,Excellent
1,202,Diya Patel,Finance,66000,2,Good
2,203,Kabir Singh,IT,60500,1,Very Good
3,204,Meera Nair,Marketing,57200,12,Excellent
4,205,Rohan Verma,Sales,52800,5,Average
5,206,Sneha Iyer,Operations,55000,4,Good
6,207,Vivaan Gupta,IT,71500,4,Excellent
7,208,Ananya Rao,Finance,63800,3,Very Good
8,209,Aryan Mehta,HR,51700,12,Good
9,210,Ishita Kapoor,Marketing,59400,2,Average

In [13]:
df.to_csv("../data/employees.csv", index=False)
print("Version 4 dataset saved successfully.")

Version 4 dataset saved successfully.

In [14]:
df_loaded = pd.read_csv("../data/employees.csv")
df_loaded

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Aarav Sharma,HR,49500,11,Excellent
1,202,Diya Patel,Finance,66000,2,Good
2,203,Kabir Singh,IT,60500,1,Very Good
3,204,Meera Nair,Marketing,57200,12,Excellent
4,205,Rohan Verma,Sales,52800,5,Average
5,206,Sneha Iyer,Operations,55000,4,Good
6,207,Vivaan Gupta,IT,71500,4,Excellent
7,208,Ananya Rao,Finance,63800,3,Very Good
8,209,Aryan Mehta,HR,51700,12,Good
9,210,Ishita Kapoor,Marketing,59400,2,Average

# Version 5 - Add New Employee Records

## Objective

Add three new employee records to the dataset. This demonstrates dataset growth by increasing the number of records while preserving the existing schema.

Changes Made:
- Added three new employee records.
- Saved the updated dataset.
- Tracked the dataset using DVC.

In [15]:
new_employees = pd.DataFrame({
    "Employee_ID": [211, 212, 213],
    "Employee_Name": [
        "Rahul Joshi",
        "Priya Deshmukh",
        "Karan Malhotra"
    ],
    "Department": [
        "IT",
        "Finance",
        "Marketing"
    ],
    "Salary": [
        62000,
        59000,
        61000
    ],
    "Years_of_Experience": [
        4,
        6,
        5
    ],
    "Performance_Rating": [
        "Good",
        "Excellent",
        "Very Good"
    ]
})

df = pd.concat([df, new_employees], ignore_index=True)
df

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Aarav Sharma,HR,49500,11,Excellent
1,202,Diya Patel,Finance,66000,2,Good
2,203,Kabir Singh,IT,60500,1,Very Good
3,204,Meera Nair,Marketing,57200,12,Excellent
4,205,Rohan Verma,Sales,52800,5,Average
5,206,Sneha Iyer,Operations,55000,4,Good
6,207,Vivaan Gupta,IT,71500,4,Excellent
7,208,Ananya Rao,Finance,63800,3,Very Good
8,209,Aryan Mehta,HR,51700,12,Good
9,210,Ishita Kapoor,Marketing,59400,2,Average
10,211,Rahul Joshi,IT,62000,4,Good
11,212,Priya Deshmukh,Finance,59000,6,Excellent
12,213,Karan Malhotra,Marketing,61000,5,Very Good

In [16]:
df.to_csv("../data/employees.csv", index=False)
print("Version 5 dataset saved successfully.")

Version 5 dataset saved successfully.

In [17]:
df_loaded = pd.read_csv("../data/employees.csv")
df_loaded

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Aarav Sharma,HR,49500,11,Excellent
1,202,Diya Patel,Finance,66000,2,Good
2,203,Kabir Singh,IT,60500,1,Very Good
3,204,Meera Nair,Marketing,57200,12,Excellent
4,205,Rohan Verma,Sales,52800,5,Average
5,206,Sneha Iyer,Operations,55000,4,Good
6,207,Vivaan Gupta,IT,71500,4,Excellent
7,208,Ananya Rao,Finance,63800,3,Very Good
8,209,Aryan Mehta,HR,51700,12,Good
9,210,Ishita Kapoor,Marketing,59400,2,Average
10,211,Rahul Joshi,IT,62000,4,Good
11,212,Priya Deshmukh,Finance,59000,6,Excellent
12,213,Karan Malhotra,Marketing,61000,5,Very Good

# Version 6 - Update Department Names

## Objective

Modify department names to reflect organizational restructuring. This demonstrates updating categorical values within the dataset.

Changes Made:
- Renamed department values.
- Saved the updated dataset.
- Tracked the dataset using DVC.

In [18]:
df["Department"] = df["Department"].replace({
    "HR": "Human Resources",
    "IT": "Engineering",
    "Finance": "Accounts & Finance",
    "Marketing": "Business Development",
    "Sales": "Sales & Marketing",
    "Operations": "Business Operations"
})
df

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Aarav Sharma,Human Resources,49500,11,Excellent
1,202,Diya Patel,Accounts & Finance,66000,2,Good
2,203,Kabir Singh,Engineering,60500,1,Very Good
3,204,Meera Nair,Business Development,57200,12,Excellent
4,205,Rohan Verma,Sales & Marketing,52800,5,Average
5,206,Sneha Iyer,Business Operations,55000,4,Good
6,207,Vivaan Gupta,Engineering,71500,4,Excellent
7,208,Ananya Rao,Accounts & Finance,63800,3,Very Good
8,209,Aryan Mehta,Human Resources,51700,12,Good
9,210,Ishita Kapoor,Business Development,59400,2,Average
10,211,Rahul Joshi,Engineering,62000,4,Good
11,212,Priya Deshmukh,Accounts & Finance,59000,6,Excellent
12,213,Karan Malhotra,Business Development,61000,5,Very Good

In [19]:
df.to_csv("../data/employees.csv", index=False)
print("Version 6 dataset saved successfully.")

Version 6 dataset saved successfully.

In [20]:
df_loaded = pd.read_csv("../data/employees.csv")
df_loaded

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Aarav Sharma,Human Resources,49500,11,Excellent
1,202,Diya Patel,Accounts & Finance,66000,2,Good
2,203,Kabir Singh,Engineering,60500,1,Very Good
3,204,Meera Nair,Business Development,57200,12,Excellent
4,205,Rohan Verma,Sales & Marketing,52800,5,Average
5,206,Sneha Iyer,Business Operations,55000,4,Good
6,207,Vivaan Gupta,Engineering,71500,4,Excellent
7,208,Ananya Rao,Accounts & Finance,63800,3,Very Good
8,209,Aryan Mehta,Human Resources,51700,12,Good
9,210,Ishita Kapoor,Business Development,59400,2,Average
10,211,Rahul Joshi,Engineering,62000,4,Good
11,212,Priya Deshmukh,Accounts & Finance,59000,6,Excellent
12,213,Karan Malhotra,Business Development,61000,5,Very Good

# Conclusion

In this assignment, dataset versioning was implemented using **Data Version Control (DVC)**.

A total of **six versions** of the employee dataset were created.

### Dataset Evolution

- Version 1: Initial Employee Salary Dataset
- Version 2: Increased employee salaries by 10%
- Version 3: Added Years_of_Experience column
- Version 4: Added Performance_Rating column
- Version 5: Added three new employee records
- Version 6: Updated department names

Each dataset version was tracked using **DVC** and committed using **Git**, allowing previous versions to be restored using Git and DVC commands.